version: '3'
services:
  article:
    image: arm64v8/mysql
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: 1234
    container_name: "batch_db"
    volumes:
      - ./article/maria:/var/lib/mysqlysql
      # init.sql
      - ./article/sql:/docker-entrypoint-initdb.d
